env1:
  name: "env1_Full_Info_Non_Rand_Size25_Rand_Starting_Pose_Obstacle"
  base_steps: 10000000
  sensor: "full information"
  sensor_range: 2
  size: 25
  min_size: 15
  random_size: true
  obstacles_random: true
  number_obstacles: 40
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
  random_coverage : true
  dataset_path: 'empty'
  load_state: false
  load_random: false