env1:
  full_information: true
  size: 5
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [2,2]
  starting_position_random : true
env2:
  full_information: true
  size: 10
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [2,2]
  starting_position_random : true


