env1:
  name: "env1_Camera_Non_Rand_Size5_Fixed_Starting_Pose"
  base_steps: 500000
  sensor: "camera"
  sensor_range: 2
  size: 5
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [3,0]
  starting_position_corner : true
  starting_position_random : false
  map_config : 'empty'
env2:
  name: "env2_Camera_Non_Rand_Size5_Rand_Starting_Pose"
  base_steps: 800000
  sensor: "camera"
  sensor_range: 2
  size: 5
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [0,4]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
env3:
  name: "env3_Camera_Info_Non_Rand_Size10_Fixed_Starting_Pose"
  base_steps: 800000
  sensor: "camera"
  sensor_range: 3
  size: 10
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [9,0]
  starting_position_corner : true
  starting_position_random : false
  map_config : 'empty'
env4:
  name: "env4_Camera_Non_Rand_Size10_Rand_Starting_Pose"
  base_steps: 1000000
  sensor: "camera"
  sensor_range: 3
  size: 10
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [9,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
env5:
  name: "env5_Camera_Non_Rand_Size15_Fixed_Starting_Pose"
  base_steps: 1000000
  sensor: "camera"
  sensor_range: 3
  size: 15
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [14,0]
  starting_position_corner : true
  starting_position_random : false
  map_config : 'empty'
env6:
  name: "env6_Camera_Non_Rand_Size15_Rand_Starting_Pose"
  base_steps: 1000000
  sensor: "camera"
  sensor_range: 3
  size: 15
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [14,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'
env7:
  name: "env7_Camera_Non_Rand_Size19_Fixed_Starting_Pose"
  base_steps: 1000000
  sensor: "camera"
  sensor_range: 3
  size: 19
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [19,0]
  starting_position_corner : true
  starting_position_random : false
  map_config : 'empty'
env8:
  name: "env8_Camera_Non_Rand_Size19_Rand_Starting_Pose"
  base_steps: 1500000
  sensor: "camera"
  sensor_range: 3
  size: 19
  min_size: 0
  random_size: false
  obstacles_random: false
  number_obstacles: 0
  starting_position: [19,0]
  starting_position_corner : false
  starting_position_random : true
  map_config : 'empty'


